// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import "package:firebase_core/firebase_core.dart"; 

class DefaultFirebaseOptions {
    static FirebaseOptions get currentPlatform{
        return const FirebaseOptions(
            apiKey: 'AIzaSyCERkwvUAcVrlol7QKaOZJCf--fNt-7R1o',
            appId: '1:992261496971:android:6bd1e c5232a02763b5b48e',
            messagingSenderId: '992261496971',
            projectId: 'flutter-se-6b6e0',
            storageBucket: 'flutter-se-6b6e0.firebasestorage.app',
            );
    }
}


//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCERkwvUAcVrlol7QKaOZJCf--fNt-7R1o',
//     appId: '1:992261496971:android:6bd1ec5232a02763b5b48e',
//     messagingSenderId: '992261496971',
//     projectId: 'flutter-se-6b6e0',
//     storageBucket: 'flutter-se-6b6e0.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDHU0lxwFL48a9N1mW70tTKJGJrTiltYxI',
//     appId: '1:992261496971:ios:1c8565426d6bb35bb5b48e',
//     messagingSenderId: '992261496971',
//     projectId: 'flutter-se-6b6e0',
//     storageBucket: 'flutter-se-6b6e0.firebasestorage.app',
//     iosBundleId: 'com.example.flutterSe',
//   );
// }
